[theme]
primaryColor = "#f63366"
# backgroundColor = "#10344b"
backgroundColor = "#fafafa"fafafa
# secondaryBackgroundColor = "#154360"
secondaryBackgroundColor = "#599191"
textColor = "#111111"
font = "sans serif"

[server]
enableStaticServing = true