[theme]
primaryColor = "#f63366"
# backgroundColor = "#10344b"
backgroundColor = "#111111"
# secondaryBackgroundColor = "#154360"
secondaryBackgroundColor = "#599191"
textColor = "#fafafa"
font = "sans serif"

[server]
enableStaticServing = true